### ISSUE TITLE
Cannot import germany-latest

### ISSUE THREAD

**Issue by giantamoeba** [mediagis/nominatim-docker#10]
Trying to import germany-latest (3GB, http://ftp5.gwdg.de/pub/misc/openstreetmap/download.geofabrik.de/germany-latest.osm.pbf)

All works fine until `Using PBF parser` where it fails after some processing:

```
Processing: Node(263768k 707.2k/s) Way(42367k 44.98k/s) Relation(0 0.00/s)COPY_END for COPY planet_osm_ways FROM STDIN;
 failed: ERROR:  could not extend file "base/16386/19189.2": No space left on device
HINT:  Check free disk space.
CONTEXT:  COPY planet_osm_ways, line 11051968

```
Maybe I am missing some docker setting? I have tried setting `"storage-opts": ["dm.basesize=100G"]` in the `/etc/docker/daemon.json`, and `/var/lib/docker` has enough space.

**Comment by thomasnordquist** [comment]
You should be aware that the image has a size of about 80GB for Germany.
The last layer is about 75GB in size, due to how docker handles the build process (docker creates a copy of the running container before applying it to the image) you'll require another 75GB of disk space.
So while building the image you'll require at least 150GB of free disk space and probably 2 days

**Comment by giantamoeba** [comment]
Thanks @thomasnordquist, trying to build with enough resources, seems to be working well.
