### ISSUE TITLE
Update broken in latest docker image

### ISSUE THREAD

**Issue by xi** [mediagis/nominatim-docker#123]
It seems like the update process does not work at all.

- `./src/build/utils/update.php --init-updates` is missing in the documentation (see #44)
- `./src/build/utils/update.php --import-osmosis-all` is failing with `RuntimeError: Open failed for '/app/src/build/osmosischange.osc': Permission denied`
- If I work around that I get the next error: `ImportError: No module named osmium`

So far my wokraround is to create a new container in regular intervals instead of updating the existing one.

**Comment by philipkozeny** [comment]
It's in the docs for 3.5 (see https://github.com/mediagis/nominatim-docker/blob/master/3.5/README.md#update)

What version of Nominatim are you using? Works for me from 3.2 to 3.5

**Comment by xi** [comment]
> What version of Nominatim are you using? Works for me from 3.2 to 3.5

I have not specified a version so I `latest` I guess

**Comment by philipkozeny** [comment]
Just to be clear: you did not build the image yourself like described in the readme but pulled it from docker hub, right? This is not an official comment since I am also just a user but I would advise you to build the image on your own.

a) the image on Ducker Hub seems outdated (I don't know what triggers the updates there)
b) while building the image the local.php is copied into your docker image - in the local.php you set what regions you want to update and in the base file it is set to Monaco. If you use the prebuilt images your update region is set to Monaco.

**Comment by xi** [comment]
> you did not build the image yourself like described in the readme but pulled it from docker hub, right?

Yes. Sorry, should have said that in the first place:

The update *as described on [docker hub](https://hub.docker.com/r/mediagis/nominatim) using the default image* does not work. I will try if it works with a different image. But I still think that issues should be fixed.

**Comment by philipkozeny** [comment]
@winsento how can we update the images on docker hub?

**Comment by xi** [comment]
I tried this with 3.4 and everything worked fine. Would still be nice if `latest` actually pointed to the latest image.

**Comment by philipkozeny** [comment]
`latest` does point to 3.5 now.
