### ISSUE TITLE
How can i add another country data??

### ISSUE THREAD

**Issue by umerfaruque** [mediagis/nominatim-docker#139]
I have installed and imported single country data and it is running successfully. Now i want to add another country data. please help me.

**Comment by JoaoGFarias** [comment]
You can merge PBF files.
Instructions [here](https://gis.stackexchange.com/a/242880)

**Comment by UntitleDude** [comment]
The above is correct and is the easiest method to import multiple countries. However, I don't see how you could use the update function for this file since it is original and may contain multiple regions.

Maybe you can use the [new importing tool from latest nominatim's version](https://nominatim.org/release-docs/develop/admin/Advanced-Installations/#importing-multiple-regions). 

You'd have to use this script inside init.sh and replace the line `sudo -u nominatim ./src/build/utils/setup.php --osm-file $OSMFILE --all --osm2pgsql-cache 8000 2>&1 --threads $THREADS && \` with the script from `utils/import_multiple_regions.sh` 

Also either change the parameter `OSMFILE` to add more files or change the nominatim script enabling you to download them before you init the database by editing it and importing it back into docker's container.

I think there's a potential upgrade to be made to this docker project, hopefully someone could take advantage of that functionality
