### ISSUE TITLE
Do I need to configure cronjobs for updates?

### ISSUE THREAD

**Issue by schmichri** [mediagis/nominatim-docker#160]
Hey @philipkozeny et al, 

sorry for the potentially stupid question but the documentation is unclear in this. 

I want to achieve constant updates (always having the latest data). Do I need to run the `./src/build/utils/update.php` as cronjob inside the container or manual or is configuring it once enough?

Documentation just says "run this command"
```
docker exec -it nominatim sudo -u postgres ./src/build/utils/update.php --import-osmosis-all
```

Would be nice if you could explain that a little bit in details. 

Thanks for the great work.

**Comment by mtmail** [comment]
The -all routine will loop until there is no more data to update, e.g. if you're 7 days behind on a daily update schedule it will run 7 updates. Then it waits 24h (`CONST_Replication_Update_Interval` seconds) and checks again for updates to apply.

So you run the command once in teh background and only need to check if it exits. Because what usually means there was an error running an update, e.g. corrupt file, network issue when downloading data or such.

Alternatively use a cronjob with `--import-osmosis` (no `-all`) which doesn't loop. You can also inspect the output of the https://github.com/osm-search/Nominatim/blob/master/utils/check_server_for_updates.py script to see if updates are available.

I assume a daily update schedule here, but it works with hourly, or minutely, or irregular, too. Depends on the data source. Default in the `local.php` is geofabrik server which only publishes daily updates.

**Comment by schmichri** [comment]
thanks a LOT for this explanation. So restarting the container would require a restart of the update command as well. Have you considered to put that in your start.sh as well? E.g. if a EnvVar is set?

**Comment by philipkozeny** [comment]
As mtmail answered, you can

a) run it with `-all` in a loop or
b) without `-all` in a cronjob

I personally run a) but with supervisor installed on my system (http://supervisord.org) to make sure that if they process gets shut down it's restarted again and I don't have to supervise the update process myself so to speak.

Here's my supervisord config if that helps:

```
[program:nominatim-update]
process_name=%(program_name)s_%(process_num)02d
command=bash -c "sleep 10 && docker exec -i nominatim sudo -u postgres ./src/build/utils/update.php --import-osmosis-all"
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/nominatim.log
```
