### ISSUE TITLE
provide external PostgreSQL support

### ISSUE THREAD

**Issue by sghaida** [mediagis/nominatim-docker#245]
**Is your feature request related to a problem? Please describe.**
this feature request  is all about maintainability of the database installation, backup

**Describe the solution you'd like**
i would like to contribute a PR to support connectivity to external Database and to be able to do so i need to update some **ENVs** and initialization scripts of the container along with the **Dockerfile** also it would be nice to contribute this pr to you so i don't need to maintain different fork for every version update. in the PR i will maintain both ways of deployments (Local DB, Remote DB).

**Describe alternatives you've considered**
on cloud provider mounting the DB on external volume using **NFS** will make sense but then we need to worry about the database backup using some external scripts , in case the volume got corrupted then we can recover.

**Additional context**
the reason for that, im trying to run the container on **AWS ECS** but running DB inside the container is limiting, and time consuming on initialization, not to mention mounting DB on external volume is not reliable, in terms if the NFS volume got corrupted

**Comment by leonardehrenfried** [comment]
Well, I would not be opposed to a feature where you override the postgres connection string via an env variable. Be aware that in such a case an empty, unused postgres instance would still be running in the container but that wouldn't be too resource intensive.

However, have you seen the comments in this similar request? https://github.com/mediagis/nominatim-docker/issues/238

Seems that you need filesystem access to the host where the database is deployed which rules out RDS, isn't it?

**Comment by robjuz** [comment]
@sghaida Just override the NOMINATIM_DATABASE_DSN variable. 

I'm doing so in my Helm chart and it works with an external database.

**Comment by mausch** [comment]
Something weird happens when initialising the container with NOMINATIM_DATABASE_DSN...
It creates and populates the database but then fails at https://github.com/mediagis/nominatim-docker/blob/2e8428ac4bb1c21a3e01fe1cdf8a13e67c174a44/4.0/init.sh#L78 as if the variable were not set?

e.g.

```
docker run -it --rm \
  -e PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf \
  -e NOMINATIM_DATABASE_DSN="pgsql:dbname=nominatim;hostaddr=192.168.0.3;user=my_user;password=my_pass" \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:4.0-d880386e3e7833363dab5b5b37fa72f6d65c9766
```

Relevant output:

```
...
+ sudo -E -u nominatim nominatim import --osm-file /nominatim/data.osm.pbf --threads 16

2022-03-17 11:45:01: Using project directory: /nominatim
2022-03-17 11:45:01: Creating database
2022-03-17 11:45:03: Setting up country tables
2022-03-17 11:45:05: Importing OSM data file
2022-03-17 11:45:05  osm2pgsql version 1.5.1
2022-03-17 11:45:05  Database version: 10.12 (Debian 10.12-2.pgdg90+1)
2022-03-17 11:45:05  PostGIS version: 2.5
2022-03-17 11:45:05  Parsing gazetteer style file '/usr/local/etc/nominatim/import-full.style'.
...
2022-03-17 11:45:14: Starting indexing rank (0 to 4) using 16 threads
...
2022-03-17 11:45:30: Done 2168/2168 in 8 @ 258.961 per second - FINISHED rank 30
...
2022-03-17 11:45:35: Recompute word counts
2022-03-17 11:45:35: Setup website at /nominatim/website
+ '[' -f tiger-nominatim-preprocessed.csv.tar.gz ']'
+ sudo -u nominatim nominatim admin --check-database
2022-03-17 11:45:35: Using project directory: /nominatim
2022-03-17 11:45:35: Checking database
Checking database connection ... Failed
Cannot connect to database: FATAL:  database "nominatim" does not exist

Hints:

* Is the database server started?
* Check the NOMINATIM_DATABASE_DSN variable in your local .env
* Try connecting to the database with the same settings

Project directory: /nominatim
Current setting of NOMINATIM_DATABASE_DSN: pgsql:dbname=nominatim
```

**Comment by leonardehrenfried** [comment]
Just guessing: the last line shows the value of NOMINATIM_DATABASE_DSN cut off after the first semicolon? Did you not copy the complete line or the bug somewhere in this area?

**Comment by mausch** [comment]
That's the whole output, I'm not cutting it off. 
It looks like it's using the default value i.e. that command doesn't seem to be picking up the env var?

**Comment by mausch** [comment]
> Seems that you need filesystem access to the host where the database is deployed which rules out RDS, doesn't it?

This requirement should go away with https://github.com/mediagis/nominatim-docker/issues/307 . 
I just need to connect to an external Postgres instance to test it :slightly_smiling_face:

**Comment by leonardehrenfried** [comment]
You could try removing the line with the database check and see what happens. Perhaps there is a bug in it. Or raise a ticket with upstream nominatim.

**Comment by mausch** [comment]
Made it work in https://github.com/mediagis/nominatim-docker/pull/308

**Comment by leonardehrenfried** [comment]
@mausch Now that #308 has been merged, would you be able to provide a little bit of documentation on how to do it?

I think a paragraph in this ticket would be enough.

**Comment by mausch** [comment]
Of course!

Here's an example command:

```
docker run -it --rm \
  -e PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf \
  -e NOMINATIM_TOKENIZER=icu \
  -e NOMINATIM_DATABASE_DSN="pgsql:dbname=nominatim;hostaddr=192.168.0.3;user=my_user;password=my_pass" \
  -e PGHOSTADDR=192.168.0.3 \
  -e PGDATABASE=nominatim \
  -e PGUSER=my_user \
  -e PGPASSWORD=my_pass \
  -p 8080:8080 \
  --name nominatim \
  mediagis/nominatim:4.0-2a43ad71ad58d3b86f0b23a535b84f71f68a53ab
```

At the moment you have to duplicate the connection details since NOMINATIM_DATABASE_DSN is used for the nominatim commands and [PGDATABASE et al](https://www.postgresql.org/docs/current/libpq-envars.html) are used for psql.
Maybe in the future there could be a script parsing NOMINATIM_DATABASE_DSN into PGDATABASE and the rest.
[This helm chart for example works the other way around: it builds the DSN from individual settings](https://github.com/robjuz/helm-charts/blob/51ca45966e789dcd171c4f68d711d23de9581c4c/charts/nominatim/templates/_helpers.tpl#L126-L132).

As you said above Postgres is still started within the container but it's not used. Maybe in the future the scripts could detect NOMINATIM_DATABASE_DSN and not start Postgres if present.

Also note that when using an external Postgres it's up to you to make sure that the tokenizer is correctly configured (either use ICU or install the tokenizer on your Postgres separately).

**Comment by MALKARAJ** [comment]
![Screenshot from 2022-08-21 23-04-06](https://user-images.githubusercontent.com/62066377/185803784-718e905d-a5f2-492a-abbd-fd860b383c9c.png)
Getting password error even though the password is correct

**Comment by mausch** [comment]
@MALKARAJ if you're trying to connect it to a postgres instance running outside the nominatim container then the hostaddr can't be 127.0.0.1

**Comment by asdfklgash** [comment]
If you want to connect to a hostname use `PGHOST` instead of `PGHOSTADDR`!

**Comment by MatsGej** [comment]
I tried moving the posgresql database used to Azure Postgresql, but ran into this errror:
pg_restore: error: could not execute query: ERROR: extension "hstore" is not allow-listed for "azure_pg_admin" users in Azure Database for PostgreSQL

The error message you're seeing indicates that the hstore extension, which is required by the public.location_property_osmline table, is not allowed for azure_pg_admin users in Azure Database for PostgreSQL.

Azure Database for PostgreSQL has a list of allowed extensions, and hstore is not included in this list for azure_pg_admin users. This is a restriction imposed by Azure for security and stability reasons.

I want to move the database to Azure Postgresql. Do yo have any suggestions?

The way I did this was to use pgadmin to create a backup of the generated postgresql database in docker and then I tried importing it into the Azure Postgresql Flexible database. I was then going to change the docker version so I could move it to Azure Container Apps. Maybe there are better ways? But I want to use the Azure Postgresql database since I have other stuff in it already! And I have to pay for it anyway.

**Comment by mtmail** [comment]
This github issue was closed 18 months ago. Problems with Azure are outside the scope of Nominatim.

**Comment by RaddishIoW** [comment]
I’ve followed the instructions posted here, and everything works - up until I try to make a call to the api to search for an address, which results in a 500 code and `nominatim@nominatim FATAL:  role "nominatim" does not exist` is printed to the logs on the nominatim docker container.

I’ve checked using psql that the user exists, and I can see the role “nominatim” listed… Any ideas on what could cause this?

**Comment by sidharth-wetter** [comment]
@RaddishIoW I am getting the same error , did you figure out whats going there??
