### ISSUE TITLE
Webserver is not accessible

### ISSUE THREAD

**Issue by galewis2** [mediagis/nominatim-docker#278]
**Describe the bug**
The standard search website isn't accessible

**To Reproduce**
1. Deploy as usual, using 3.7.2

**Expected behavior**
Get the webmap of the search interface

**Screenshots & Logs**
If applicable, add screenshots & logs to help explain your problem.

**Comment by mtmail** [comment]
The HTML interface https://github.com/osm-search/nominatim-ui is a separate project starting Nominatim 3.6 (https://github.com/osm-search/Nominatim/releases/tag/v3.6.0)

**Comment by philipkozeny** [comment]
That's intended, Nominatim moved the website (UI) to a separate project, see https://nominatim.org/admin/Setup-Nominatim-UI/. 

The default installation is just the API now, so in addition you can run the nominatim-ui project to have access to the website.

**Comment by galewis2** [comment]
I guess it might help to make it more clear that Nominatim-UI is needed for the GUI, especially since this used to be the case? I've happily been using the earlier images, but given the behaviour changed, it would be worth to mention nominatim-ui

**Comment by leonardehrenfried** [comment]
Sounds like a good docs update. Would you like to contribute it?

If you need the feature you could send a PR which adds it, however the last time I looked at it, it was a little tricky to realiably set the correct hostname it should connect to because in the docker container you don't it. Maybe it has changed though.
