### ISSUE TITLE
v 3.3 Failed to establish database connection:SQLSTATE[08006] [7] FATAL:  role "www-data" does not exist

### ISSUE THREAD

**Issue by mesmeric-fiend** [mediagis/nominatim-docker#65]
What I do:

cd /opt/mediagis/nominatim-docker/3.3
docker build -t nominatim .
cd /opt/osrm/src
wget http://download.geofabrik.de/asia/maldives-latest.osm.pbf

docker run -t -v /opt/osrm/src:/data nominatim  sh /app/init.sh /data/maldives-latest.osm.pbf postgresdata 4

docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim -v /opt/osrm/src/postgresdata:/var/lib/postgresql/9.5/main nominatim bash /app/start.sh

[root@localhost src]# curl 'http://localhost:7070'

`<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        em { font-weight: bold; font-family: monospace; color: #e00404; background-color: #ffeaea; }
    </style>
</head>
<body>
    <h1>Internal Server Error</h1>

        <p>Nominatim has encountered an internal error while accessing the database.
           This may happen because the database is broken or because of a bug in
           the software.</p>

    <h3>Details</h3>

    Failed to establish database connection:SQLSTATE[08006] [7] FATAL:  role "www-data" does not exist

    <p>
        If you feel this error is incorrect feel file an issue on
        <a href="https://github.com/openstreetmap/Nominatim/issues">Github</a>.

        Please include the error message above and the URL you used.
    </p>
</body>
</html>
`

**Comment by nakendlom** [comment]
Just ecountered the same error a day before. It took me several hours to find out the reason. There is an error in docker hub docs. The last image uses Postgress 11 and you the data directory changed. It must be 
docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim -v /opt/osrm/src/postgresdata:/var/lib/postgresql/**11**/main nominatim bash /app/start.sh 
instead of
docker run --restart=always -p 6432:5432 -p 7070:8080 -d --name nominatim -v /opt/osrm/src/postgresdata:/var/lib/postgresql/**9.5**/main nominatim bash /app/start.sh

**Comment by mesmeric-fiend** [comment]
Thank you? it's worked.
