### ISSUE TITLE
how to push the OSM data to Postgress installed machine from local machine ?

### ISSUE THREAD

**Issue by mathavan-m** [mediagis/nominatim-docker#95]
we have pogtgres server separately. now we want to push the OSM data (PBF data) to the postgres server(another machine) via docker from the local machine .we installed docker in local machine. how to sent the data ?

**Comment by mathavan-m** [comment]
any update on this ?

**Comment by philipkozeny** [comment]
Not 100% sure what you mean, but you could set the connection in your local.php: https://github.com/mediagis/nominatim-docker/blob/bd9e01a6ea9b8a86cb3a57ac02047ce86d75e263/3.5/local.php#L12

Would work a bit different in 3.6, since the way we work with the config file changed. If this doesn't help or is still unsolved, feel three to reopen the issue, thanks!
